name: CI

on:
  push:
    branches: [ "AdvKit" ]
  pull_request:
    branches: [ "AdvKit" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    container: wpilib/roborio-cross-ubuntu:2023-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      # Grant exec perms for ./gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Run only build tasks without tests, that way we can build the JNIs first that the tests depend on
      - name: Gradle Build
        run: ./gradlew build -x check --max-workers 2
      # Run Gradle Tests.
      - name: Gradle Tests
        run: ./gradlew test --max-workers 1 --stacktrace
      # Upload Gradle Test Report.
      - name: Upload Gradle Test Report
        uses: actions/upload-artifact@v3
        with:
          name: gradle-test-report
          path: build/reports/tests/test/index.html
